const express = require("express");
const { connectedDb } = require("./config/db");
const LikeRoutes = require("./routes/likes");
const ProfessionRoutes = require("./routes/professions");
const { swaggerUi, swaggerDocs } = require("./swagger");
const UsersRoute = require("./routes/user");
const RegionRoute = require("./routes/regions");
const SubjectRoute = require("./routes/subjects");
const app = express();
app.use(express.json());
connectedDb();
app.use("/likes", LikeRoutes);
app.use("/professions", ProfessionRoutes);
app.use("/users", UsersRoute);
app.use("/regions", RegionRoute);
app.use("/subjects", SubjectRoute);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocs));
app.listen(3000, () => console.log("server started on port 3000"));
